# Generated by Django 5.0.6 on 2025-04-18 18:44

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mrn', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BabyFacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=api.models.face_photo_upload)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baby')),
            ],
        ),
        migrations.CreateModel(
            name='BabyFootPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.footprint_upload)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baby')),
            ],
        ),
        migrations.CreateModel(
            name='BabyRetinaPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.retina_upload)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baby')),
            ],
        ),
        migrations.CreateModel(
            name='BottleQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_number', models.PositiveIntegerField()),
                ('unique_number', models.CharField(max_length=100, unique=True)),
                ('qr_code_image', models.ImageField(upload_to=api.models.qr_code_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baby')),
            ],
        ),
        migrations.CreateModel(
            name='EBMBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expressed', models.DateField()),
                ('date_delivered', models.DateField()),
                ('bottle_number', models.PositiveIntegerField()),
                ('unique_number', models.CharField(max_length=100, unique=True)),
                ('volume_ml', models.FloatField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baby')),
            ],
        ),
        migrations.CreateModel(
            name='EBMUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_used_ml', models.FloatField()),
                ('discarded_volume_ml', models.FloatField(blank=True, null=True)),
                ('ebm_bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ebmbottle')),
            ],
        ),
        migrations.CreateModel(
            name='MotherID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.ImageField(upload_to=api.models.mother_id_upload)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.baby')),
            ],
        ),
        migrations.CreateModel(
            name='MotherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('mother_mrn', models.CharField(max_length=50)),
                ('gravida', models.PositiveSmallIntegerField()),
                ('para', models.PositiveSmallIntegerField()),
                ('abortion', models.PositiveSmallIntegerField()),
                ('delivery_date', models.DateField()),
                ('delivery_type', models.CharField(choices=[('Normal', 'Normal Vaginal Delivery'), ('C-Section', 'C-Section')], default='Normal', max_length=10)),
                ('baby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse1_id', models.CharField(max_length=50)),
                ('nurse2_id', models.CharField(blank=True, max_length=50, null=True)),
                ('method_used', models.CharField(max_length=50)),
                ('verified_by_nurse2', models.BooleanField(default=False)),
                ('verification_result', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baby')),
                ('bottle_qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bottleqrcode')),
            ],
        ),
    ]
