# Generated by Django 5.0.6 on 2025-04-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkverification',
            old_name='match_with_mother',
            new_name='verify_face_with_qr',
        ),
        migrations.RenameField(
            model_name='milkverification',
            old_name='reprint_required',
            new_name='verify_footprint_with_qr',
        ),
        migrations.AddField(
            model_name='milkverification',
            name='verify_mother_id_or_fingerprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milkverification',
            name='verify_retina_with_qr',
            field=models.BooleanField(default=False),
        ),
    ]
